import Head from "next/head";
import Layout from "../components/shared/Layout";
import styles from "../styles/About.module.css";
export default function About() {
    return (
        <Layout>
            <Head>
                <title>Gandom software group</title>
                <meta name="description" content="Generated by mohammadreza gohari" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="description">Mohammadreza Gohari</div>
        </Layout>
    )
};


export const